'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),os=require('node:os');const {spawn}=require('node:child_process');const {Readable,Transform}=require('node:stream');const {pipeline}=require('node:stream/promises');
const {patchNative,VERSION}=require('./native-patch.cjs');
const manifest=require('../shared/build-assets.json');const EXE='Yu_Gi_Oh_Forbidden_Memories_Recompiled.exe';let child=null,canceled=false;
function cancelBuild(){canceled=true;if(child){spawn('taskkill.exe',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});}}
function run(exe,args,options,log,onLine=()=>{}){if(canceled)return Promise.reject(Error('Preparación cancelada.'));return new Promise((resolve,reject)=>{const p=spawn(exe,args,{...options,windowsHide:true,shell:false,stdio:['ignore','pipe','pipe']});child=p;let pending='';for(const stream of [p.stdout,p.stderr])stream.on('data',b=>{fs.appendFileSync(log,b);pending+=b.toString();const lines=pending.split(/\r?\n/);pending=lines.pop();for(const line of lines)onLine(line);});p.once('error',reject);p.once('close',code=>{if(child===p)child=null;code===0?resolve():reject(Error(canceled?'Preparación cancelada.':'No se pudo terminar la preparación. Podés volver a intentarlo; el progreso y los guardados se conservan.'));});});}
function psQuote(s){return "'"+s.replaceAll("'","''")+"'";}
async function unzip(zip,dest,log){fs.mkdirSync(dest,{recursive:true});await run('powershell.exe',['-NoProfile','-NonInteractive','-Command','Expand-Archive -LiteralPath '+psQuote(zip)+' -DestinationPath '+psQuote(dest)+' -Force'],{},log);}
async function verify(file,expected){const hash=crypto.createHash('sha256');for await(const b of fs.createReadStream(file))hash.update(b);if(hash.digest('hex')!==expected)throw Error('Un archivo de preparación no pasó la verificación. Volvé a instalar el programa.');}
async function download(url,file,hash,onProgress){if(fs.existsSync(file)){await verify(file,hash);return;}const r=await fetch(url,{signal:AbortSignal.timeout(600000)});if(!r.ok)throw Error('No pudimos descargar los archivos de preparación. Revisá la conexión y probá de nuevo.');const total=Number(r.headers.get('content-length'));let bytes=0,last=-1;try{await pipeline(Readable.fromWeb(r.body),new Transform({transform(b,e,cb){if(canceled){cb(Error('Preparación cancelada.'));return;}bytes+=b.length;const n=total?Math.floor(bytes/total*100):null;if(n!==last){last=n;onProgress({stage:'Descargando herramientas de preparación (solo una vez)…',progress:n});}cb(null,b);}}),fs.createWriteStream(file+'.partial'));await verify(file+'.partial',hash);fs.renameSync(file+'.partial',file);}catch(e){fs.rmSync(file+'.partial',{force:true});throw e;}}
async function buildRuntime(root,data,disc,onProgress=()=>{},options={}){
 canceled=false;const work=path.join(data,'native-0.5.9'),project=path.join(work,'project'),build=path.join(project,'build-release'),exe=path.join(build,EXE),marker=path.join(work,'.complete');
 if(fs.existsSync(marker)&&fs.readFileSync(marker,'utf8')===VERSION&&fs.existsSync(exe)){stageBoot(project,build);return exe;}
 fs.mkdirSync(work,{recursive:true});const log=path.join(work,'preparation.log');fs.writeFileSync(log,'Forbidden Memories Amigos local preparation\n');
 const vendor=process.resourcesPath&&fs.existsSync(path.join(process.resourcesPath,'vendor','ygofm-setup-0.5.9.zip'))?path.join(process.resourcesPath,'vendor'):path.join(root,'vendor');
 let toolchain=options.toolchain||path.join(work,'toolchain');
 if(!fs.existsSync(path.join(toolchain,'bin','cmake.exe'))){const zip=path.join(work,'toolchain.zip');await download(manifest.toolchain.url,zip,manifest.toolchain.sha256,onProgress);onProgress({stage:'Preparando las herramientas…',progress:null});await unzip(zip,toolchain,log);if(!fs.existsSync(path.join(toolchain,'bin','cmake.exe'))){const nested=fs.readdirSync(toolchain,{withFileTypes:true}).find(d=>d.isDirectory()&&fs.existsSync(path.join(toolchain,d.name,'bin','cmake.exe')));if(nested)toolchain=path.join(toolchain,nested.name);}}
 if(!fs.existsSync(path.join(project,'.unpacked'))){onProgress({stage:'Preparando los archivos del programa…',progress:null});const zip=path.join(vendor,'ygofm-setup-0.5.9.zip');await verify(zip,manifest['ygofm-setup-0.5.9.zip']);await unzip(zip,project,log);fs.writeFileSync(path.join(project,'.unpacked'),'1');}
 patchNative(project);
 const python=path.join(toolchain,'python','python.exe');if(!fs.existsSync(python))throw Error('La preparación de las herramientas quedó incompleta. Volvé a intentarlo.');
 const pillow=path.join(work,'python-packages');if(!fs.existsSync(path.join(pillow,'PIL'))){const zip=path.join(vendor,'pillow-312.zip');await verify(zip,manifest['pillow-312.zip']);await unzip(zip,pillow,log);}
 const env={...process.env,PATH:path.join(toolchain,'bin')+';'+path.dirname(python)+';'+process.env.PATH,PYTHONPATH:pillow,PYTHONUTF8:'1',RETCOMM_TOOLCHAIN_DIR:toolchain,PSXRECOMP_TOOLCHAIN_DIR:toolchain,CMAKE_BUILD_PARALLEL_LEVEL:String(Math.max(1,Math.min(4,os.availableParallelism?.()||4))),PSX_PORTABLE:'1'};
 // Never modify the user's PATH registry; use the portable compiler in this process only.
 const cli=path.join(project,'psxrecomp','psxrecomp_cli.py'),common=['--project-root',project,'--config',path.join(project,'game.toml'),'--json-progress'];
 onProgress({stage:'Preparando el juego a partir de tu disco…',progress:null});
 await run(python,[cli,'generate',...common,'--disc',disc,'--no-toolchain-download'],{cwd:project,env},log);
 onProgress({stage:'Armando el juego en esta PC. Puede tardar varios minutos…',progress:null});
 await run(python,[cli,'rebuild',...common,'--build-dir',build,'--exe-basename','Yu_Gi_Oh_Forbidden_Memories_Recompiled','--disc',disc,'--no-pgo','--no-toolchain-download','--cmake-extra=-DPSX_DEBUG_TOOLS=ON','--cmake-extra=-DPython3_EXECUTABLE='+python],{cwd:project,env},log);
 if(!fs.existsSync(exe))throw Error('No se encontró el juego preparado. Volvé a intentar.');stageBoot(project,build);fs.writeFileSync(marker,VERSION);fs.writeFileSync(path.join(build,'.amigos-runtime-v5'),VERSION);onProgress({stage:'Juego listo',progress:100});return exe;
}
function stageBoot(project,build){const target=path.join(build,'disc','SLUS_014.11');if(!fs.existsSync(target)){fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(path.join(project,'disc','SLUS_014.11'),target);}}
module.exports={buildRuntime,cancelBuild};
